/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	taskqueuev1alpha1 "github.com/taskqueue/pkg/apis/taskqueue/v1alpha1"
	versioned "github.com/taskqueue/pkg/client/clientset/versioned"
	internalinterfaces "github.com/taskqueue/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/taskqueue/pkg/client/listers/taskqueue/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TaskQueueInformer provides access to a shared informer and lister for
// TaskQueues.
type TaskQueueInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.TaskQueueLister
}

type taskQueueInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTaskQueueInformer constructs a new informer for TaskQueue type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTaskQueueInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTaskQueueInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTaskQueueInformer constructs a new informer for TaskQueue type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTaskQueueInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TaskqueueV1alpha1().TaskQueues(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TaskqueueV1alpha1().TaskQueues(namespace).Watch(options)
			},
		},
		&taskqueuev1alpha1.TaskQueue{},
		resyncPeriod,
		indexers,
	)
}

func (f *taskQueueInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTaskQueueInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *taskQueueInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&taskqueuev1alpha1.TaskQueue{}, f.defaultInformer)
}

func (f *taskQueueInformer) Lister() v1alpha1.TaskQueueLister {
	return v1alpha1.NewTaskQueueLister(f.Informer().GetIndexer())
}
