/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/taskqueue/pkg/apis/taskqueue/v1alpha1"
	scheme "github.com/taskqueue/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TaskQueuesGetter has a method to return a TaskQueueInterface.
// A group's client should implement this interface.
type TaskQueuesGetter interface {
	TaskQueues(namespace string) TaskQueueInterface
}

// TaskQueueInterface has methods to work with TaskQueue resources.
type TaskQueueInterface interface {
	Create(*v1alpha1.TaskQueue) (*v1alpha1.TaskQueue, error)
	Update(*v1alpha1.TaskQueue) (*v1alpha1.TaskQueue, error)
	UpdateStatus(*v1alpha1.TaskQueue) (*v1alpha1.TaskQueue, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.TaskQueue, error)
	List(opts v1.ListOptions) (*v1alpha1.TaskQueueList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TaskQueue, err error)
	TaskQueueExpansion
}

// taskQueues implements TaskQueueInterface
type taskQueues struct {
	client rest.Interface
	ns     string
}

// newTaskQueues returns a TaskQueues
func newTaskQueues(c *TaskqueueV1alpha1Client, namespace string) *taskQueues {
	return &taskQueues{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the taskQueue, and returns the corresponding taskQueue object, and an error if there is any.
func (c *taskQueues) Get(name string, options v1.GetOptions) (result *v1alpha1.TaskQueue, err error) {
	result = &v1alpha1.TaskQueue{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("taskqueues").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TaskQueues that match those selectors.
func (c *taskQueues) List(opts v1.ListOptions) (result *v1alpha1.TaskQueueList, err error) {
	result = &v1alpha1.TaskQueueList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("taskqueues").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested taskQueues.
func (c *taskQueues) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("taskqueues").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a taskQueue and creates it.  Returns the server's representation of the taskQueue, and an error, if there is any.
func (c *taskQueues) Create(taskQueue *v1alpha1.TaskQueue) (result *v1alpha1.TaskQueue, err error) {
	result = &v1alpha1.TaskQueue{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("taskqueues").
		Body(taskQueue).
		Do().
		Into(result)
	return
}

// Update takes the representation of a taskQueue and updates it. Returns the server's representation of the taskQueue, and an error, if there is any.
func (c *taskQueues) Update(taskQueue *v1alpha1.TaskQueue) (result *v1alpha1.TaskQueue, err error) {
	result = &v1alpha1.TaskQueue{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("taskqueues").
		Name(taskQueue.Name).
		Body(taskQueue).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *taskQueues) UpdateStatus(taskQueue *v1alpha1.TaskQueue) (result *v1alpha1.TaskQueue, err error) {
	result = &v1alpha1.TaskQueue{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("taskqueues").
		Name(taskQueue.Name).
		SubResource("status").
		Body(taskQueue).
		Do().
		Into(result)
	return
}

// Delete takes name of the taskQueue and deletes it. Returns an error if one occurs.
func (c *taskQueues) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("taskqueues").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *taskQueues) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("taskqueues").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched taskQueue.
func (c *taskQueues) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TaskQueue, err error) {
	result = &v1alpha1.TaskQueue{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("taskqueues").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
