/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/taskqueue/pkg/apis/taskqueue/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTaskQueues implements TaskQueueInterface
type FakeTaskQueues struct {
	Fake *FakeTaskqueueV1alpha1
	ns   string
}

var taskqueuesResource = schema.GroupVersionResource{Group: "taskqueue.com", Version: "v1alpha1", Resource: "taskqueues"}

var taskqueuesKind = schema.GroupVersionKind{Group: "taskqueue.com", Version: "v1alpha1", Kind: "TaskQueue"}

// Get takes name of the taskQueue, and returns the corresponding taskQueue object, and an error if there is any.
func (c *FakeTaskQueues) Get(name string, options v1.GetOptions) (result *v1alpha1.TaskQueue, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(taskqueuesResource, c.ns, name), &v1alpha1.TaskQueue{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TaskQueue), err
}

// List takes label and field selectors, and returns the list of TaskQueues that match those selectors.
func (c *FakeTaskQueues) List(opts v1.ListOptions) (result *v1alpha1.TaskQueueList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(taskqueuesResource, taskqueuesKind, c.ns, opts), &v1alpha1.TaskQueueList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TaskQueueList{ListMeta: obj.(*v1alpha1.TaskQueueList).ListMeta}
	for _, item := range obj.(*v1alpha1.TaskQueueList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested taskQueues.
func (c *FakeTaskQueues) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(taskqueuesResource, c.ns, opts))

}

// Create takes the representation of a taskQueue and creates it.  Returns the server's representation of the taskQueue, and an error, if there is any.
func (c *FakeTaskQueues) Create(taskQueue *v1alpha1.TaskQueue) (result *v1alpha1.TaskQueue, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(taskqueuesResource, c.ns, taskQueue), &v1alpha1.TaskQueue{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TaskQueue), err
}

// Update takes the representation of a taskQueue and updates it. Returns the server's representation of the taskQueue, and an error, if there is any.
func (c *FakeTaskQueues) Update(taskQueue *v1alpha1.TaskQueue) (result *v1alpha1.TaskQueue, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(taskqueuesResource, c.ns, taskQueue), &v1alpha1.TaskQueue{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TaskQueue), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTaskQueues) UpdateStatus(taskQueue *v1alpha1.TaskQueue) (*v1alpha1.TaskQueue, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(taskqueuesResource, "status", c.ns, taskQueue), &v1alpha1.TaskQueue{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TaskQueue), err
}

// Delete takes name of the taskQueue and deletes it. Returns an error if one occurs.
func (c *FakeTaskQueues) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(taskqueuesResource, c.ns, name), &v1alpha1.TaskQueue{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTaskQueues) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(taskqueuesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.TaskQueueList{})
	return err
}

// Patch applies the patch and returns the patched taskQueue.
func (c *FakeTaskQueues) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TaskQueue, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(taskqueuesResource, c.ns, name, data, subresources...), &v1alpha1.TaskQueue{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TaskQueue), err
}
